### ISSUE TITLE
train_h3wb.npz

### ISSUE THREAD

**Issue by imbamaker** [valeoai/PAFUSE#3]
can you offer train_h3wb.npz? thanks.

**Comment by nerminsamet** [comment]
Hello, 

You can download the data from the [this link](https://drive.google.com/file/d/1LZh4Jsg3_ZKBF0iEPiexzoGHE4srLgfC/view). 

For download links and more information on H3WB dataset you could check the official [H3WB repository](https://github.com/wholebody3d/wholebody3d).
